# The following test sequence tests the sequence of examples in
# getting-started.md.

###
OPTIONS {{service}} HTTP/1.0
Storage: {{storage_getting_started}}

> {%
client.test("unittest", function() {
    client.assert(response.headers.valueOf("Trace-Composite-Hash") === "7b630b90ee568519ea506ac932eb30ad");
});
%}

###
PUT {{service}}/table%5Bnot(guests)%5D::last HTTP/1.0
Storage: {{storage_getting_started}}
Content-Type: application/xml

<guests>
  <persons/>
  <conversation/>
</guests>

> {%
client.test("unittest", function() {
    client.assert(response.headers.valueOf("Trace-Composite-Hash") === "d8408525270baba2abb8e374e7ab6d2b");
});
%}

###
PUT {{service}}/table/guests/persons::last HTTP/1.0
Storage: {{storage_getting_started}}
Content-Type: application/xml

<person name="John Doe" mail="john.doe@example.local"/>

> {%
client.test("unittest", function() {
    client.assert(response.headers.valueOf("Trace-Composite-Hash") === "d6c6147ce56904d7c2f002fa264f7275");
});
%}

###
OPTIONS {{service}} HTTP/1.0
Storage: {{storage_getting_started}}

> {%
client.test("unittest", function() {
    client.assert(response.headers.valueOf("Trace-Composite-Hash") === "88c6c79b3a617996023501a2833081e5");
});
%}

###
PUT {{service}}/table%5Bnot(guests)%5D::last HTTP/1.0
Storage: {{storage_getting_started}}
Content-Type: application/xml

<guests>
  <persons/>
  <conversation/>
</guests>

> {%
client.test("unittest", function() {
    client.assert(response.headers.valueOf("Trace-Composite-Hash") === "27b741e92b34f5783b47043dd8d50967");
});
%}

###
PUT {{service}}/table/guests/persons::last HTTP/1.0
Storage: {{storage_getting_started}}
Content-Type: application/xml

<person name="Jane Doe" mail="jane.doe@example.local"/>

> {%
client.test("unittest", function() {
    client.assert(response.headers.valueOf("Trace-Composite-Hash") === "f22708f42a4fca3b9e64a2c87c373cd8");
});
%}

###
PUT {{service}}/table/guests/persons::last HTTP/1.0
Storage: {{storage_getting_started}}
Content-Type: application/xml

<person name="Mike Ross" mail="mike.ross@example.local"/>

> {%
client.test("unittest", function() {
    client.assert(response.headers.valueOf("Trace-Composite-Hash") === "fa44de41ada84c44b8d108c4b500fb52");
});
%}

###
PUT {{service}}/table/guests/persons::last HTTP/1.0
Storage: {{storage_getting_started}}
Content-Type: application/xml

<person name="Dan Star" mail="dan.star@example.local"/>

> {%
client.test("unittest", function() {
    client.assert(response.headers.valueOf("Trace-Composite-Hash") === "da25e8e80134bbe9c271166c9e9792c4");
});
%}

###
OPTIONS {{service}} HTTP/1.0
Storage: {{storage_getting_started}}

> {%
client.test("unittest", function() {
    client.assert(response.headers.valueOf("Trace-Composite-Hash") === "2b0a379129ee44ed89284a2af113775d");
});
%}

###
GET  {{service}}count(/table/guests/persons/person)%3E1 HTTP/1.0
Storage: {{storage_getting_started}}

> {%
client.test("unittest", function() {
    client.assert(response.headers.valueOf("Trace-Composite-Hash") === "055cf6a1c13a9eae06b4aab1ca167f92");
});
%}

###
PUT {{service}}/table/guests/conversation::last HTTP/1.0
Storage: {{storage_getting_started}}
Content-Type: application/xml

<message from="dan.star@example.local">
    Where do you come from?</message>

> {%
client.test("unittest", function() {
    client.assert(response.headers.valueOf("Trace-Composite-Hash") === "bfafef3448aff766f0d33be4a3d7ecee");
});
%}

###
PUT {{service}}/table/guests/conversation::last HTTP/1.0
Storage: {{storage_getting_started}}
Content-Type: application/xml

<message from="john.doe@example.local">
    I'm from Hempstead and have a small bookstore.</message>

> {%
client.test("unittest", function() {
    client.assert(response.headers.valueOf("Trace-Composite-Hash") === "1a1b436b679180581ecc276ec577acf7");
});
%}

###
PUT {{service}}/table/guests/conversation::last HTTP/1.0
Storage: {{storage_getting_started}}
Content-Type: application/xml

<message from="jane.doe@example.local">
    I live in Long Island and have an antique store.</message>

> {%
client.test("unittest", function() {
    client.assert(response.headers.valueOf("Trace-Composite-Hash") === "529c92197ad3598e37d21bd8c1b4e10f");
});
%}

###
PUT {{service}}/table/guests/conversation::last HTTP/1.0
Storage: {{storage_getting_started}}
Content-Type: application/xml

<message from="mike.ross@example.local">
    I live in Queens, work for a shipping company on a cargo ship.</message>

> {%
client.test("unittest", function() {
    client.assert(response.headers.valueOf("Trace-Composite-Hash") === "7f3f04c4777ad1c782879931e57f9388");
});
%}

###
PUT {{service}}/table/guests/conversation::last HTTP/1.0
Storage: {{storage_getting_started}}
Content-Type: application/xml

<message from="dan.star@example.local">
    I work and live in Yonkers as a gardener.</message>

> {%
client.test("unittest", function() {
    client.assert(response.headers.valueOf("Trace-Composite-Hash") === "fda42e03b981e228e23e744bdc1064ba");
});
%}

###
PUT {{service}}/table/guests/conversation::last HTTP/1.0
Storage: {{storage_getting_started}}
Content-Type: application/xml

<message from="dan.star@example.local">
    In this beautiful weather I arrived with my scooter.</message>

> {%
client.test("unittest", function() {
    client.assert(response.headers.valueOf("Trace-Composite-Hash") === "066a773cb38561414a4b7f64a8733d3f");
});
%}

###
PUT {{service}}/table/guests/conversation::last HTTP/1.0
Storage: {{storage_getting_started}}
Content-Type: application/xml

<message from="dan.star@example.local">
    I like to look at the city.</message>

> {%
client.test("unittest", function() {
    client.assert(response.headers.valueOf("Trace-Composite-Hash") === "26c12c94822938d2a1943c87be9c3325");
});
%}

###
# - URI: //conversation/message[position()<=count(//conversation/message)-5]
DELETE {{service}}0x2f2f636f6e766572736174696f6e2f6d6573736167655b706f736974696f6e28293c3d636f756e74282f2f636f6e766572736174696f6e2f6d657373616765292d355d HTTP/1.0
Storage: {{storage_getting_started}}

> {%
client.test("unittest", function() {
    client.assert(response.headers.valueOf("Trace-Composite-Hash") === "010605cd237af9d5afd3e7fc644a20d1");
});
%}

###
# - URI: //message[@from='dan.star@example.local']
GET {{service}}0x2f2f6d6573736167655b4066726f6d3d2764616e2e73746172406578616d706c652e6c6f63616c275d HTTP/1.0
Storage: {{storage_getting_started}}

> {%
client.test("unittest", function() {
    client.assert(response.headers.valueOf("Trace-Composite-Hash") === "702e9bcc4f805b2bd7d8ff29652314a8");
});
%}

###
# - URI: //*/@mail|//*/@from
GET {{service}}0x2f2f2a2f406d61696c7c2f2f2a2f4066726f6d HTTP/1.0
Storage: {{storage_getting_started}}

> {%
client.test("unittest", function() {
    client.assert(response.headers.valueOf("Trace-Composite-Hash") === "59b8c47f22623594442c77a46a7d6922");
});
%}

###
POST {{service}} HTTP/1.0
Storage: {{storage_getting_started}}
Content-Type: application/xslt+xml

<?xml version="1.0"?>
<xsl:stylesheet version="1.0"
    xmlns:xsl="http://www.w3.org/1999/XSL/Transform">
  <xsl:output method="text"/>
  <xsl:template match="/">
    <xsl:for-each select="//persons/person">
Mame: <xsl:value-of select="@name"/>
Mail: <xsl:value-of select="@mail"/>
Messages:
      <xsl:variable name="mail" select="@mail"/>
      <xsl:choose>
        <xsl:when test="count(//message[@from=$mail]) &gt; 0">
          <xsl:for-each select="//message[@from=$mail]">
            <xsl:value-of select="."/>
          </xsl:for-each>
    ----
        </xsl:when>
        <xsl:otherwise>
    No messages
    ----
        </xsl:otherwise>
      </xsl:choose>
    </xsl:for-each>
  </xsl:template>
</xsl:stylesheet>

> {%
client.test("unittest", function() {
    client.assert(response.headers.valueOf("Trace-Composite-Hash") === "e8f0c38ab78dfe17482b2cb611fad923");
});
%}

###
