###
# initDatasource
# Initialization from the first player
# Expectations:
# - Status code 201 Resource Created
# - Storage-Revision: 1/1
# - Storage-Space: 262144/72 bytes
PUT {{service}} HTTP/1.0
Storage: {{storage_snake}}

> {%
client.test("unittest", function() {
    client.assert(response.headers.valueOf("Trace-Request-Hash") === "b064518214ba578ef590d162ae445172");
    client.assert(response.headers.valueOf("Trace-Request-Header-Hash") === "c2c2ae6de80b51f3244ca7c0d1c71a4c");
    client.assert(response.headers.valueOf("Trace-Request-Data-Hash") === "d41d8cd98f00b204e9800998ecf8427e");
    client.assert(response.headers.valueOf("Trace-Response-Hash") === "eece7445b364079bf7390ad5912594ed");
    client.assert(response.headers.valueOf("Trace-Response-Header-Hash") === "88d31e43d149f144fc9c43b6e7a7fea9");
    client.assert(response.headers.valueOf("Trace-Response-Data-Hash") === "d41d8cd98f00b204e9800998ecf8427e");
    client.assert(response.headers.valueOf("Trace-Storage-Hash") === "6731214dd1b6c96c5a47c2bcb8bddf13");
});
%}

###
# initStorage
# Initialization from the first player
# Expectations:
# - Status code 204 No Content
# - Storage-Revision: 2/10
# - Storage-Space: 262144/664 bytes
PUT {{service}}/snake%5Bnot(players)%5D%5Bnot(board)%5D::last HTTP/1.0
Storage: {{storage_snake}}
Content-Type: application/xml

<players timeout="5000">
  <a color="#000000" touch=""/>
  <b color="#0000FF" touch=""/>
  <c color="#00FF00" touch=""/>
  <d color="#00FFFF" touch=""/>
  <e color="#FF0000" touch=""/>
  <f color="#FF00FF" touch=""/>
  <g color="#FFFF00" touch=""/>
  <h color="#FFFFFF" touch=""/>
</players>
<board rows="31" cols="51"/>

> {%
client.test("unittest", function() {
    client.assert(response.headers.valueOf("Trace-Request-Hash") === "3a1980267def8cbe67f91308e29a19cf");
    client.assert(response.headers.valueOf("Trace-Request-Header-Hash") === "f9d8c5bb76cd4d55e07d0baa8871089f");
    client.assert(response.headers.valueOf("Trace-Request-Data-Hash") === "a622551b8a21651ab24e5724451af7ff");
    client.assert(response.headers.valueOf("Trace-Response-Hash") === "64f43500716633427b914befe29c8f49");
    client.assert(response.headers.valueOf("Trace-Response-Header-Hash") === "1aaf1eb6085ad599439d3bc0e1ffbe0e");
    client.assert(response.headers.valueOf("Trace-Response-Data-Hash") === "d41d8cd98f00b204e9800998ecf8427e");
    client.assert(response.headers.valueOf("Trace-Storage-Hash") === "fb7a5ddef06d3258451cf645ffa7c8c4");
});
%}

###
# initDatasource
# Initialization from another player
# Expectations:
# - Status code 204 No Content
# - Storage-Revision: 2/0
# - Storage-Space: 262144/664 bytes
PUT {{service}} HTTP/1.0
Storage: {{storage_snake}}

> {%
client.test("unittest", function() {
    client.assert(response.headers.valueOf("Trace-Request-Hash") === "b064518214ba578ef590d162ae445172");
    client.assert(response.headers.valueOf("Trace-Request-Header-Hash") === "c2c2ae6de80b51f3244ca7c0d1c71a4c");
    client.assert(response.headers.valueOf("Trace-Request-Data-Hash") === "d41d8cd98f00b204e9800998ecf8427e");
    client.assert(response.headers.valueOf("Trace-Response-Hash") === "64f43500716633427b914befe29c8f49");
    client.assert(response.headers.valueOf("Trace-Response-Header-Hash") === "626e5ebe7741e4425451c4abeae12d6a");
    client.assert(response.headers.valueOf("Trace-Response-Data-Hash") === "d41d8cd98f00b204e9800998ecf8427e");
    client.assert(response.headers.valueOf("Trace-Storage-Hash") === "fb7a5ddef06d3258451cf645ffa7c8c4");
});
%}

###
# initStorage
# Initialization from another player
# Expectations:
# - Status code 304 Not Modified
# - Storage-Revision: 2/0
# - Storage-Space: 262144/664 bytes
PUT {{service}}/snake%5Bnot(players)%5D%5Bnot(board)%5D::last HTTP/1.0
Storage: {{storage_snake}}
Content-Type: application/xml

<players timeout="5000">
  <a color="#000000" touch=""/>
  <b color="#0000FF" touch=""/>
  <c color="#00FF00" touch=""/>
  <d color="#00FFFF" touch=""/>
  <e color="#FF0000" touch=""/>
  <f color="#FF00FF" touch=""/>
  <g color="#FFFF00" touch=""/>
  <h color="#FFFFFF" touch=""/>
</players>
<board rows="31" cols="51"/>

> {%
client.test("unittest", function() {
    client.assert(response.headers.valueOf("Trace-Request-Hash") === "3a1980267def8cbe67f91308e29a19cf");
    client.assert(response.headers.valueOf("Trace-Request-Header-Hash") === "f9d8c5bb76cd4d55e07d0baa8871089f");
    client.assert(response.headers.valueOf("Trace-Request-Data-Hash") === "a622551b8a21651ab24e5724451af7ff");
    client.assert(response.headers.valueOf("Trace-Response-Hash") === "252335a4e294acfa119704fa344ec477");
    client.assert(response.headers.valueOf("Trace-Response-Header-Hash") === "626e5ebe7741e4425451c4abeae12d6a");
    client.assert(response.headers.valueOf("Trace-Response-Data-Hash") === "d41d8cd98f00b204e9800998ecf8427e");
    client.assert(response.headers.valueOf("Trace-Storage-Hash") === "fb7a5ddef06d3258451cf645ffa7c8c4");
});
%}

###
# readPlayers
# Expectations:
# - Status code 200 Success
# - Storage-Revision: 2/0
# - Storage-Space: 262144/664 bytes
# - Content-Type: application/json
# - Content-Length: 694
GET {{service}}/snake/players!json HTTP/1.0
Storage: {{storage_snake}}

> {%
client.test("unittest", function() {
    client.assert(response.headers.valueOf("Trace-Request-Hash") === "db0c9ce5719010f8fc60b3de84efafd2");
    client.assert(response.headers.valueOf("Trace-Request-Header-Hash") === "f55648bc0f0428ea6e2e0d63c6c58483");
    client.assert(response.headers.valueOf("Trace-Request-Data-Hash") === "d41d8cd98f00b204e9800998ecf8427e");
    client.assert(response.headers.valueOf("Trace-Response-Hash") === "6ea793edc825cd6b0da28cb2d1217a47");
    client.assert(response.headers.valueOf("Trace-Response-Header-Hash") === "1189412976a1409db242cdc595a560ce");
    client.assert(response.headers.valueOf("Trace-Response-Data-Hash") === "6200ae2b573c454e9214061e1d16e459");
    client.assert(response.headers.valueOf("Trace-Storage-Hash") === "fb7a5ddef06d3258451cf645ffa7c8c4");
});
%}

###
# readBoard
# Expectations:
# - Status code 200 Success
# - Storage-Revision: 2/0
# - Storage-Space: 262144/664 bytes
# - Content-Type: application/json
# - Content-Length: 70
GET {{service}}/snake/board!json HTTP/1.0
Storage: {{storage_snake}}

> {%
client.test("unittest", function() {
    client.assert(response.headers.valueOf("Trace-Request-Hash") === "c6e96cd274483434204d2c61b748ee84");
    client.assert(response.headers.valueOf("Trace-Request-Header-Hash") === "f55648bc0f0428ea6e2e0d63c6c58483");
    client.assert(response.headers.valueOf("Trace-Request-Data-Hash") === "d41d8cd98f00b204e9800998ecf8427e");
    client.assert(response.headers.valueOf("Trace-Response-Hash") === "6ea793edc825cd6b0da28cb2d1217a47");
    client.assert(response.headers.valueOf("Trace-Response-Header-Hash") === "9cc3bbf68ece5aec7b73d4ee680bc64c");
    client.assert(response.headers.valueOf("Trace-Response-Data-Hash") === "b208c13c6eba9993e25ab9066daa8716");
    client.assert(response.headers.valueOf("Trace-Storage-Hash") === "fb7a5ddef06d3258451cf645ffa7c8c4");
});
%}

###
# initTouchUpdate
# Expectations:
# - Status code 204 No Content
# - Storage-Revision: 3/1
# - Storage-Space: 262144/667 bytes
# - URI: //a/@touch
PATCH {{service}}?2f2f612f40746f756368 HTTP/1.0
Storage: {{storage_snake}}
Content-Type: text/plain

100

> {%
client.test("unittest", function() {
    client.assert(response.headers.valueOf("Trace-Request-Hash") === "49343de6c926cb5e5777062fc8ab54ce");
    client.assert(response.headers.valueOf("Trace-Request-Header-Hash") === "6eeebf131031df800d5160fc3374c92a");
    client.assert(response.headers.valueOf("Trace-Request-Data-Hash") === "f899139df5e1059396431415e770c6dd");
    client.assert(response.headers.valueOf("Trace-Response-Hash") === "64f43500716633427b914befe29c8f49");
    client.assert(response.headers.valueOf("Trace-Response-Header-Hash") === "667392bfa4d5b8973ffdae097606111e");
    client.assert(response.headers.valueOf("Trace-Response-Data-Hash") === "d41d8cd98f00b204e9800998ecf8427e");
    client.assert(response.headers.valueOf("Trace-Storage-Hash") === "012705fcd8645e0f47edf861d410c963");
});
%}

###
# initTouchUpdate
# Expectations:
# - Status code 204 No Content
# - Storage-Revision: 4/1
# - Storage-Space: 262144/670 bytes
# - URI: //b/@touch
PATCH {{service}}?2f2f622f40746f756368 HTTP/1.0
Storage: {{storage_snake}}
Content-Type: text/plain

200

> {%
client.test("unittest", function() {
    client.assert(response.headers.valueOf("Trace-Request-Hash") === "695aa503de5aff4c77ef62572d18dc68");
    client.assert(response.headers.valueOf("Trace-Request-Header-Hash") === "6eeebf131031df800d5160fc3374c92a");
    client.assert(response.headers.valueOf("Trace-Request-Data-Hash") === "3644a684f98ea8fe223c713b77189a77");
    client.assert(response.headers.valueOf("Trace-Response-Hash") === "64f43500716633427b914befe29c8f49");
    client.assert(response.headers.valueOf("Trace-Response-Header-Hash") === "3a65eedc32f0e4e1189a9fcd3117dfb1");
    client.assert(response.headers.valueOf("Trace-Response-Data-Hash") === "d41d8cd98f00b204e9800998ecf8427e");
    client.assert(response.headers.valueOf("Trace-Storage-Hash") === "a0f85a749e2f41a03d0b7e7301d10ea7");
});
%}

###
# initTouchUpdate
# Expectations:
# - Status code 204 No Content
# - Storage-Revision: 5/1
# - Storage-Space: 262144/673 bytes
# - URI: //c/@touch
PATCH {{service}}?2f2f632f40746f756368 HTTP/1.0
Storage: {{storage_snake}}
Content-Type: text/plain

300

> {%
client.test("unittest", function() {
    client.assert(response.headers.valueOf("Trace-Request-Hash") === "241378dd6c69169ea942f71e0c002b99");
    client.assert(response.headers.valueOf("Trace-Request-Header-Hash") === "6eeebf131031df800d5160fc3374c92a");
    client.assert(response.headers.valueOf("Trace-Request-Data-Hash") === "94f6d7e04a4d452035300f18b984988c");
    client.assert(response.headers.valueOf("Trace-Response-Hash") === "64f43500716633427b914befe29c8f49");
    client.assert(response.headers.valueOf("Trace-Response-Header-Hash") === "5eebc459198f2b37b33b0fed2a4cb024");
    client.assert(response.headers.valueOf("Trace-Response-Data-Hash") === "d41d8cd98f00b204e9800998ecf8427e");
    client.assert(response.headers.valueOf("Trace-Storage-Hash") === "399a5373208e3c6ea22e1e55a297ffda");
});
%}

###
# initTouchUpdate
# Expectations:
# - Status code 204 No Content
# - Storage-Revision: 6/1
# - Storage-Space: 262144/676 bytes
# - URI: //d/@touch
PATCH {{service}}?2f2f642f40746f756368 HTTP/1.0
Storage: {{storage_snake}}
Content-Type: text/plain

400

> {%
client.test("unittest", function() {
    client.assert(response.headers.valueOf("Trace-Request-Hash") === "a42d120eccf17d79d19b900ce2ec8c50");
    client.assert(response.headers.valueOf("Trace-Request-Header-Hash") === "6eeebf131031df800d5160fc3374c92a");
    client.assert(response.headers.valueOf("Trace-Request-Data-Hash") === "18d8042386b79e2c279fd162df0205c8");
    client.assert(response.headers.valueOf("Trace-Response-Hash") === "64f43500716633427b914befe29c8f49");
    client.assert(response.headers.valueOf("Trace-Response-Header-Hash") === "40aa74f70acaa92a83bb113cd9bf1d49");
    client.assert(response.headers.valueOf("Trace-Response-Data-Hash") === "d41d8cd98f00b204e9800998ecf8427e");
    client.assert(response.headers.valueOf("Trace-Storage-Hash") === "47ddb4e2ccbb38ac4b1eca41bd106b27");
});
%}

###
# initTouchUpdate
# Expectations:
# - Status code 204 No Content
# - Storage-Revision: 7/1
# - Storage-Space: 262144/676 bytes
# - URI: //a/@touch
PATCH {{service}}?2f2f612f40746f756368 HTTP/1.0
Storage: {{storage_snake}}
Content-Type: text/plain

500

> {%
client.test("unittest", function() {
    client.assert(response.headers.valueOf("Trace-Request-Hash") === "49343de6c926cb5e5777062fc8ab54ce");
    client.assert(response.headers.valueOf("Trace-Request-Header-Hash") === "6eeebf131031df800d5160fc3374c92a");
    client.assert(response.headers.valueOf("Trace-Request-Data-Hash") === "cee631121c2ec9232f3a2f028ad5c89b");
    client.assert(response.headers.valueOf("Trace-Response-Hash") === "64f43500716633427b914befe29c8f49");
    client.assert(response.headers.valueOf("Trace-Response-Header-Hash") === "9c3d3c745993bfe49734d35c0cca4b0e");
    client.assert(response.headers.valueOf("Trace-Response-Data-Hash") === "d41d8cd98f00b204e9800998ecf8427e");
    client.assert(response.headers.valueOf("Trace-Storage-Hash") === "948b21abbe595e524ae16fe8d8f387a1");
});
%}

###
# initKeyboardControl
# Expectations:
# - Status code 204 No Content
# - Storage-Revision: 8/3
# - Storage-Space: 262144/858 bytes
# - URI: //players[not(//field[@id=1])]//a
PATCH {{service}}?2f2f706c61796572735b6e6f74282f2f6669656c645b4069643d315d295d2f2f61 HTTP/1.0
Storage: {{storage_snake}}
Content-Type: application/xml

<field id="11" player="a"/><field id="12" player="a"/><field id="13" player="a"/>

> {%
client.test("unittest", function() {
    client.assert(response.headers.valueOf("Trace-Request-Hash") === "40e8f39ad62e90059074691370a1c257");
    client.assert(response.headers.valueOf("Trace-Request-Header-Hash") === "9653cf008d4cf1a2bb5a797288e8dbb5");
    client.assert(response.headers.valueOf("Trace-Request-Data-Hash") === "9c8949c12ff18869cc23e18d0f80efc9");
    client.assert(response.headers.valueOf("Trace-Response-Hash") === "64f43500716633427b914befe29c8f49");
    client.assert(response.headers.valueOf("Trace-Response-Header-Hash") === "2cc218b3ff0f376d71804ca9b095392b");
    client.assert(response.headers.valueOf("Trace-Response-Data-Hash") === "d41d8cd98f00b204e9800998ecf8427e");
    client.assert(response.headers.valueOf("Trace-Storage-Hash") === "d5c7aa1a078c57fcbae3e3cacf59c0d7");
});
%}

###
# initKeyboardControl
# Expectations:
# - Status code 204 No Content
# - Storage-Revision: 9/3
# - Storage-Space: 262144/1040 bytes
# - URI: //players[not(//field[@id=1])]//b
PATCH {{service}}?2f2f706c61796572735b6e6f74282f2f6669656c645b4069643d315d295d2f2f62 HTTP/1.0
Storage: {{storage_snake}}
Content-Type: application/xml

<field id="21" player="b"/><field id="22" player="b"/><field id="23" player="b"/>

> {%
client.test("unittest", function() {
    client.assert(response.headers.valueOf("Trace-Request-Hash") === "067a3cbde1fec45c40b1929423ebf5a5");
    client.assert(response.headers.valueOf("Trace-Request-Header-Hash") === "9653cf008d4cf1a2bb5a797288e8dbb5");
    client.assert(response.headers.valueOf("Trace-Request-Data-Hash") === "d34c908204ca9949958d2a4171d2ad1b");
    client.assert(response.headers.valueOf("Trace-Response-Hash") === "64f43500716633427b914befe29c8f49");
    client.assert(response.headers.valueOf("Trace-Response-Header-Hash") === "7779952b081db5eff71fa8d717374bc3");
    client.assert(response.headers.valueOf("Trace-Response-Data-Hash") === "d41d8cd98f00b204e9800998ecf8427e");
    client.assert(response.headers.valueOf("Trace-Storage-Hash") === "ef9f0ac776c89b0156a2fc6f3fb051f6");
});
%}

###
# initScreenUpdate
# Expectations:
# - Status code 200 Success
# - Storage-Revision: 9/0
# - Storage-Space: 262144/1040 bytes
# - Content-Type: application/json
# - Content-Length: 425
# - URI: //players//field!json
GET {{service}}?2f2f706c61796572732f2f6669656c64216a736f6e HTTP/1.0
Storage: {{storage_snake}}

> {%
client.test("unittest", function() {
    client.assert(response.headers.valueOf("Trace-Request-Hash") === "b14dc2a7675b3f1da0e638569bd3c57d");
    client.assert(response.headers.valueOf("Trace-Request-Header-Hash") === "f55648bc0f0428ea6e2e0d63c6c58483");
    client.assert(response.headers.valueOf("Trace-Request-Data-Hash") === "d41d8cd98f00b204e9800998ecf8427e");
    client.assert(response.headers.valueOf("Trace-Response-Hash") === "6ea793edc825cd6b0da28cb2d1217a47");
    client.assert(response.headers.valueOf("Trace-Response-Header-Hash") === "004a12bebb3be5cb1937e9d5958bd9f9");
    client.assert(response.headers.valueOf("Trace-Response-Data-Hash") === "fb554f652c75153ae1e04f4122521c4a");
    client.assert(response.headers.valueOf("Trace-Storage-Hash") === "ef9f0ac776c89b0156a2fc6f3fb051f6");
});
%}

###
# initPlayersCleanUp
# Expectations:
# - Status code 204 No Content
# - Storage-Revision: 10/6
# - Storage-Space: 262144/884 bytes
# - URI: //players/*[@touch<400]|//players/*[@touch='']
PATCH {{service}}?2f2f706c61796572732f2a5b40746f7563683c3430305d7c2f2f706c61796572732f2a5b40746f7563683d27275d HTTP/1.0
Storage: {{storage_snake}}
Content-Type: text/plain

> {%
client.test("unittest", function() {
    client.assert(response.headers.valueOf("Trace-Request-Hash") === "7e4800ed6c161f92cd8d2325f1057959");
    client.assert(response.headers.valueOf("Trace-Request-Header-Hash") === "9983f74a850dbb21a50235a885895ae6");
    client.assert(response.headers.valueOf("Trace-Request-Data-Hash") === "d41d8cd98f00b204e9800998ecf8427e");
    client.assert(response.headers.valueOf("Trace-Response-Hash") === "64f43500716633427b914befe29c8f49");
    client.assert(response.headers.valueOf("Trace-Response-Header-Hash") === "88cd41d87b153b69a870a8b7172fe83c");
    client.assert(response.headers.valueOf("Trace-Response-Data-Hash") === "d41d8cd98f00b204e9800998ecf8427e");
    client.assert(response.headers.valueOf("Trace-Storage-Hash") === "122372f4b3ea066e8ad8c6e69ac37b6c");
});
%}

###
# initPlayersCleanUp
# Expectations:
# - Status code 204 No Content
# - Storage-Revision: 11/2
# - Storage-Space: 262144/860 bytes
# - URI: //players/*[@touch<400]/@touch
PATCH {{service}}?2f2f706c61796572732f2a5b40746f7563683c3430305d2f40746f756368 HTTP/1.0
Storage: {{storage_snake}}
Content-Type: text/plain

> {%
client.test("unittest", function() {
    client.assert(response.headers.valueOf("Trace-Request-Hash") === "6b8b5dce5201db6abed282ab49aced27");
    client.assert(response.headers.valueOf("Trace-Request-Header-Hash") === "9983f74a850dbb21a50235a885895ae6");
    client.assert(response.headers.valueOf("Trace-Request-Data-Hash") === "d41d8cd98f00b204e9800998ecf8427e");
    client.assert(response.headers.valueOf("Trace-Response-Hash") === "64f43500716633427b914befe29c8f49");
    client.assert(response.headers.valueOf("Trace-Response-Header-Hash") === "494fb695494602af9009f1f737c31c96");
    client.assert(response.headers.valueOf("Trace-Response-Data-Hash") === "d41d8cd98f00b204e9800998ecf8427e");
    client.assert(response.headers.valueOf("Trace-Storage-Hash") === "9a6f7dee0dc9f02e675df2870427f87e");
});
%}

###
# join
# Get the next free player through set touch
# Expectations:
# - Status code 204 No Content
# - Storage-Revision: 12/1
# - Storage-Space: 262144/863 bytes
# - URI: //players/*[@touch=''][1]/@touch
PATCH {{service}}?2f2f706c61796572732f2a5b40746f7563683d27275d5b315d2f40746f756368 HTTP/1.0
Storage: {{storage_snake}}
Content-Type: text/plain

700

> {%
client.test("unittest", function() {
    client.assert(response.headers.valueOf("Trace-Request-Hash") === "966c778bb83ccfcd6077834170849b9f");
    client.assert(response.headers.valueOf("Trace-Request-Header-Hash") === "6eeebf131031df800d5160fc3374c92a");
    client.assert(response.headers.valueOf("Trace-Request-Data-Hash") === "e5841df2166dd424a57127423d276bbe");
    client.assert(response.headers.valueOf("Trace-Response-Hash") === "64f43500716633427b914befe29c8f49");
    client.assert(response.headers.valueOf("Trace-Response-Header-Hash") === "c130c726fbb2428bef99d5f5690c216b");
    client.assert(response.headers.valueOf("Trace-Response-Data-Hash") === "d41d8cd98f00b204e9800998ecf8427e");
    client.assert(response.headers.valueOf("Trace-Storage-Hash") === "3b1a5f5c4d5633e249ce191fada354ad");
});
%}

###
# join
# H wants to put on the start position, but only if free, but it is occupied
# Expectations:
# - Status code 304 Not Modified
# - Storage-Revision: 12/0
# - Storage-Space: 262144/863 bytes
# - URI: /snake[not(//field/@id=11)]//h
PATCH  {{service}}?2f736e616b655b6e6f74282f2f6669656c642f4069643d3131295d2f2f68 HTTP/1.0
Storage: {{storage_snake}}
Content-Type: application/xml

<field id="11" player="h"/>

> {%
client.test("unittest", function() {
    client.assert(response.headers.valueOf("Trace-Request-Hash") === "363ad0e22efb274d7c3af577e8a1fd3e");
    client.assert(response.headers.valueOf("Trace-Request-Header-Hash") === "5bc355a71347d20187dd45851ae7f458");
    client.assert(response.headers.valueOf("Trace-Request-Data-Hash") === "c9498c6970b8b7bc1ab3d641eaf9580a");
    client.assert(response.headers.valueOf("Trace-Response-Hash") === "252335a4e294acfa119704fa344ec477");
    client.assert(response.headers.valueOf("Trace-Response-Header-Hash") === "33809df17666e6e8edb6adc3faeb8e0d");
    client.assert(response.headers.valueOf("Trace-Response-Data-Hash") === "d41d8cd98f00b204e9800998ecf8427e");
    client.assert(response.headers.valueOf("Trace-Storage-Hash") === "3b1a5f5c4d5633e249ce191fada354ad");
});
%}

###
# initKeyboardControl
# A Moves one to the right
# Expectations:
# - Status code 204 No Content
# - Storage-Revision: 13/3
# - Storage-Space: 262144/870 bytes
# - URI: //players[not(//field[@id=14])]//a
PATCH {{service}}?2f2f706c61796572735b6e6f74282f2f6669656c645b4069643d31345d295d2f2f61 HTTP/1.0
Storage: {{storage_snake}}
Content-Type: application/xml

<field id="12" player="a"/><field id="13" player="a"/><field id="14" player="a"/>

> {%
client.test("unittest", function() {
    client.assert(response.headers.valueOf("Trace-Request-Hash") === "aa995efb237dcffeeec27a5bf3d913d3");
    client.assert(response.headers.valueOf("Trace-Request-Header-Hash") === "9653cf008d4cf1a2bb5a797288e8dbb5");
    client.assert(response.headers.valueOf("Trace-Request-Data-Hash") === "f532a0946fb34c86e7fb62cd8879387e");
    client.assert(response.headers.valueOf("Trace-Response-Hash") === "64f43500716633427b914befe29c8f49");
    client.assert(response.headers.valueOf("Trace-Response-Header-Hash") === "87669fbef67f2e71306de56fadb47cb5");
    client.assert(response.headers.valueOf("Trace-Response-Data-Hash") === "d41d8cd98f00b204e9800998ecf8427e");
    client.assert(response.headers.valueOf("Trace-Storage-Hash") === "938476ecd9f030a47aedd010f9ab6a77");
});
%}

###
# join
# H wants to put on the start position, but only if free, and it is free, because A has moved
# Expectations:
# - Status code 204 No Content
# - Storage-Revision: 14/1
# - Storage-Space: 262144/938 bytes
# - URI: /snake[not(//field/@id=11)]//h
PATCH  {{service}}?2f736e616b655b6e6f74282f2f6669656c642f4069643d3131295d2f2f68 HTTP/1.0
Storage: {{storage_snake}}
Content-Type: application/xml

<field id="11" player="h"/>

> {%
client.test("unittest", function() {
    client.assert(response.headers.valueOf("Trace-Request-Hash") === "363ad0e22efb274d7c3af577e8a1fd3e");
    client.assert(response.headers.valueOf("Trace-Request-Header-Hash") === "5bc355a71347d20187dd45851ae7f458");
    client.assert(response.headers.valueOf("Trace-Request-Data-Hash") === "c9498c6970b8b7bc1ab3d641eaf9580a");
    client.assert(response.headers.valueOf("Trace-Response-Hash") === "64f43500716633427b914befe29c8f49");
    client.assert(response.headers.valueOf("Trace-Response-Header-Hash") === "cf507788286540b5b84cc79aa803c7c9");
    client.assert(response.headers.valueOf("Trace-Response-Data-Hash") === "d41d8cd98f00b204e9800998ecf8427e");
    client.assert(response.headers.valueOf("Trace-Storage-Hash") === "523f552304851d62c06cb667d5219572");
});
%}

###
# initKeyboardControl
# B moves one up and collides
# Expectations:
# - Status code 304 Not Modified
# - Storage-Revision: 14/0
# - Storage-Space: 262144/938 bytes
# - URI: //players[not(//field[@id=14])]//b
PATCH {{service}}?2f2f706c61796572735b6e6f74282f2f6669656c645b4069643d31345d295d2f2f62 HTTP/1.0
Storage: {{storage_snake}}
Content-Type: application/xml

<field id="22" player="b"/><field id="23" player="b"/><field id="14" player="b"/>

> {%
client.test("unittest", function() {
    client.assert(response.headers.valueOf("Trace-Request-Hash") === "ace528a3fa2d4664dac773320ce8e561");
    client.assert(response.headers.valueOf("Trace-Request-Header-Hash") === "9653cf008d4cf1a2bb5a797288e8dbb5");
    client.assert(response.headers.valueOf("Trace-Request-Data-Hash") === "c49e6180cadc6f7c45e96f16cf2325fe");
    client.assert(response.headers.valueOf("Trace-Response-Hash") === "252335a4e294acfa119704fa344ec477");
    client.assert(response.headers.valueOf("Trace-Response-Header-Hash") === "d62e71a7176bd52928a6b1357870c1db");
    client.assert(response.headers.valueOf("Trace-Response-Data-Hash") === "d41d8cd98f00b204e9800998ecf8427e");
    client.assert(response.headers.valueOf("Trace-Storage-Hash") === "523f552304851d62c06cb667d5219572");
});
%}
