openapi: 3.0.1
info:
  title: "Seanox XMEX - XML-Micro-Exchange"
  version: "1.3.0"
  description: "
XML-Micro-Exchange is a volatile NoSQL stateless micro datasource for the
Internet. It is designed for easy communication and data exchange of
web-applications and for IoT or for other Internet-based modules and
components.<br>
The XML based datasource is volatile and lives through continuous use and
expires through inactivity. They are designed for active and near real-time data
exchange but not as a real-time capable long-term storage.<br>
Compared to a JSON storage, this datasource supports more dynamics, partial data
access, data transformation, and volatile short-term storage.

<h1>API</h1>
The API uses the HTTP.

The URI typically contains a noticeable separator to divide it into context
path and XPath.

For the API only the XPath is relevant.

<pre>
https://xmex.seanox.com/xmex!xpath(-function)<br>
<-------------------------->|<--------------><br>
&#160;       Context Path              XPath<br>
</pre>

In some cases, the XPath syntax may not be supported as a URI by the client or
provider.<br>
In these cases, the XPath can alternatively be used as a query string or
hexadecimal or Base64 encoded.

<pre>
https://xmex.seanox.com/xmex!count(//items[@id<0])<br>
https://xmex.seanox.com/xmex!count(%2F%2Fitems[@id<0])<br>
https://xmex.seanox.com/xmex!0x636F756E74282F2F6974656D735B4069643C305D29<br>
https://xmex.seanox.com/xmex!Base64:Y291bnQoLy9pdGVtc1tAaWQ8MF0p<br>
</pre>

The request supports the following additional headers:

<pre>
Storage                   Storage identifier optional with name of the root element<br>
Accept-Effects            Controls the content of Storage Effects header<br>
</pre>

Also the reponse has additional headers:

<pre>
Connection-Unique          Unique ID created by the API to mark client owner data<br>
Storage                    Storage identifier without the name of the root element<br>
Storage-Revision           Current revision of the storage<br>
Storage-Space              Capacity of the storage (total/used in bytes)<br>
Storage-Last-Modified      Timestamp (RFC822) of the last access<br>
Storage-Expiration         Timestamp (RFC822) when the storage will expire<br>
Storage-Expiration-Time    Idle time in milliseconds until storage expires<br>
Storage-Effects            For PUT/PATCH/DELETE, UUIDs directly affected by the request<br>
Execution-Time             Duration of request processing in milliseconds<br>
Error                      Unique error number from the logging with status 500<br>
Message                    Detailed error message with status 400 / 422
</pre>
<b>
  Notice about response code 404, this always refers to the storage, but never
  to an addressed target in the storage.<br>
  If a target does not exist, requests are responded to with code 204.
</b>
<br><br>
  "
  termsOfService: "https://raw.githubusercontent.com/seanox/xml-micro-exchange-js/master/TERMS%20OF%20SERVICE"
  contact:
    email: "xmex@seanox.com"
  license:
    name: "Apache 2.0"
    url: "http://www.apache.org/licenses/LICENSE-2.0.html"
externalDocs:
  description: Find out more about Seanox XMEX
  url: https://github.com/seanox/xml-micro-exchange-js
servers:
  - url: https://xmex.seanox.com
  - url: http://127.0.0.1:8000
tags:
  - name: "API"
paths:
  /xmex!:
    options:
      tags:
        - API
      responses:
        404:
        500:
  /xmex!{xpath}:
    options:
      tags:
        - API
      parameters:
        - name: xpath
          in: path
          description: ID of pet to return
          required: true
          schema:
            type: string
      responses:
        404:
        500:
    put:
      tags:
        - API
      parameters:
        - name: xpath
          in: path
          description: ID of pet to return
          required: true
          schema:
            type: string
      responses:
        404:
        500:
    patch:
      tags:
        - API
      parameters:
        - name: xpath
          in: path
          description: ID of pet to return
          required: true
          schema:
            type: string
      responses:
        404:
        500:
    get:
      tags:
        - API
      parameters:
        - name: xpath
          in: path
          description: ID of pet to return
          required: true
          schema:
            type: string
      responses:
        404:
        500:
    post:
      tags:
        - API
      parameters:
        - name: xpath
          in: path
          description: ID of pet to return
          required: true
          schema:
            type: string
      responses:
        404:
        500:
    delete:
      tags:
        - API
      parameters:
        - name: xpath
          in: path
          description: ID of pet to return
          required: true
          schema:
            type: string
      responses:
        404:
        500:
  /xmex!{xpath}!json:
    get:
      tags:
        - API
      parameters:
        - name: xpath
          in: path
          description: ID of pet to return
          required: true
          schema:
            type: string
      responses:
        404:
        500:
    post:
      tags:
        - API
      parameters:
        - name: xpath
          in: path
          description: ID of pet to return
          required: true
          schema:
            type: string
      responses:
        404:
        500:
